/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICrowdSourcing,
  ICrowdSourcingInterface,
} from "../ICrowdSourcing";

const _abi = [
  {
    inputs: [],
    name: "donaToCause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getDonorsList",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_purpose",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_targetamount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_deployer",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICrowdSourcing__factory {
  static readonly abi = _abi;
  static createInterface(): ICrowdSourcingInterface {
    return new utils.Interface(_abi) as ICrowdSourcingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICrowdSourcing {
    return new Contract(address, _abi, signerOrProvider) as ICrowdSourcing;
  }
}
