/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "CrowdSourcing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrowdSourcing__factory>;
    getContractFactory(
      name: "CrowdSourcingFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrowdSourcingFactory__factory>;
    getContractFactory(
      name: "ICrowdSourcing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICrowdSourcing__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "CrowdSourcing",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrowdSourcing>;
    getContractAt(
      name: "CrowdSourcingFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrowdSourcingFactory>;
    getContractAt(
      name: "ICrowdSourcing",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICrowdSourcing>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
